[tool.poetry]
name = "ipython-gpt"
version = "0.0.1"
description = "A Jupyter/IPython extension to use ChatGPT"
authors = ["Santiago Basulto <santiago.basulto@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.2"

[tool.poetry.dev-dependencies]
ipython = "^8.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
